//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedExpenseApplicationDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SharedExpenseDBEntities : DbContext
    {
        public SharedExpenseDBEntities()
            : base("name=SharedExpenseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<ApplicationUserInformation> ApplicationUserInformations { get; set; }
        public virtual DbSet<ExpenseType> ExpenseTypes { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserLogIn> UserLogIns { get; set; }
        public virtual DbSet<GroupExpense> GroupExpenses { get; set; }
    }
}
