CREATE TABLE [dbo].[Status]
(
	[StatusId] INT NOT NULL IDENTITY PRIMARY KEY, 
    [StatusDescription] VARCHAR(10) NOT NULL,
	[CreateDate] DATETIME2 NOT NULL DEFAULT GETDATE(), 
    [LastUpdate] DATETIME2 NOT NULL DEFAULT GETDATE()
)
